let data = [

    {id:1,name:"Authentication Module",
    purpose:"User security User security User security  User security",
    description:"Manages user login, registration, and session handling with precission",
    date:"2024-01-15 12:30pm",checked:false},

    { id:2,name:"Payment Gateway",purpose:"Transaction processing Transaction processing Transaction processing",description:"Integrates payment systems for secure online transactions",date:"2024-02-05 12:30pm",checked:false},
    { id:3,name:"Notification System",purpose:"User engagement User engagement  User engagement User engagement",description:"Sends alerts and notifications via email, SMS, or push notifications",date:"2024-03-10 12:30pm",checked:false},
    { id:4,name:"Analytics Dashboard",purpose:"Data visualization Data visualization Data visualization Data visualization",description:"Displays metrics and KPIs to monitor business performance",date:"2024-04-12 12:30pm",checked:false},
    { id:5,name:"API Gateway Gateway",purpose:"Middleware for services Middleware for services Middleware for services",description:"Routes, authenticates, and processes API requests efficiently",date:"2024-05-22 12:30pm",checked:false},
    { id:6,name:"Inventory Manager",purpose:"Stock tracking Stock tracking  Stock tracking Stock tracking ",description:"Routes, authenticates, and processes API requests efficiently",date:"2024-06-15 12:30pm",checked:false},
    { id:7,name:"Chatbot Assistant",purpose:"User interaction automation User interaction automation",description:"Provides automated responses and assistance to user queries",date:"2024-07-20 12:30pm",checked:false},
    { id:8,name:"Logging System",purpose:"Application monitoring Application monitoring Application monitoring",description:"Captures application logs for debugging and performance monitoring",date:"2024-08-01 12:30pm",checked:false},
    { id:9,name:"User Profile Manager",purpose:"Data management Data management Data management",description:"Handles user details, preferences, and account settingsand account settingsand account settingsand account settings",date:"2024-09-18 12:30pm",checked:false},
    { id:10,name:"Content Management",purpose:"Website management Website management Website management",description:"Organizes, updates, and publishes website content dynamically",date:"2024-10-15 12:30pm",checked:false},
    { id: 11, name: "AI Recommendation", purpose: "Personalized suggestions Personalized suggestions", description: "Provides AI-driven recommendations based on user behavior", date: "2024-11-05 12:30pm", checked: false },
    { id: 12, name: "Backup Service", purpose: "Data protection Data protection Data protection", description: "Automates system backups and ensures data recovery", date: "2024-12-10 12:30pm", checked: false },
    { id: 13, name: "Email Marketing", purpose: "Customer engagement Customer engagement", description: "Manages email campaigns and audience targeting", date: "2025-01-22 12:30pm", checked: false },
    { id: 14, name: "Fraud Detection", purpose: "Security Security Security", description: "Identifies and prevents fraudulent activities", date: "2025-02-15 12:30pm", checked: false },
    { id: 15, name: "SEO Optimization", purpose: "Search ranking Search ranking", description: "Enhances website visibility for search engines", date: "2025-03-05 12:30pm", checked: false },
    { id: 16, name: "Live Streaming", purpose: "Real-time content Real-time content", description: "Enables live video streaming with minimal latency", date: "2025-04-18 12:30pm", checked: false },
    { id: 17, name: "Push Notification", purpose: "Instant alerts Instant alerts", description: "Delivers push notifications to keep users engaged", date: "2025-05-27 12:30pm", checked: false },
    { id: 18, name: "Survey Forms", purpose: "User feedback User feedback", description: "Collects and analyzes user survey responses", date: "2025-06-13 12:30pm", checked: false },
    { id: 19, name: "File Manager", purpose: "File organization File organization", description: "Manages file uploads, storage, and retrieval", date: "2025-07-09 12:30pm", checked: false },
    { id: 20, name: "Event Scheduler", purpose: "Task planning Task planning", description: "Schedules and automates events or tasks", date: "2025-08-25 12:30pm", checked: false },
    { id: 21, name: "Social Sharing", purpose: "Social engagement Social engagement", description: "Enables easy sharing of content on social media", date: "2025-09-17 12:30pm", checked: false },
    { id: 22, name: "Geo Location", purpose: "Location tracking Location tracking", description: "Provides location-based services and tracking", date: "2025-10-14 12:30pm", checked: false },
    { id: 23, name: "Multi Factor Auth", purpose: "Security Security", description: "Enhances login security with multi-factor authentication", date: "2025-11-11 12:30pm", checked: false },
    { id: 24, name: "AI Chatbot", purpose: "Automated support Automated support", description: "Provides AI-powered automated customer support", date: "2025-12-08 12:30pm", checked: false },
    { id: 25, name: "E-commerce Platform", purpose: "Online sales Online sales", description: "Manages online store transactions and product catalogs", date: "2026-01-06 12:30pm", checked: false },
    { id: 26, name: "HR Management", purpose: "Employee tracking Employee tracking", description: "Manages HR tasks like payroll and attendance", date: "2026-02-02 12:30pm", checked: false },
    { id: 27, name: "Legal Compliance", purpose: "Regulation adherence Regulation adherence", description: "Ensures company compliance with legal regulations", date: "2026-03-15 12:30pm", checked: false },
    { id: 28, name: "Data Encryption", purpose: "Security Security", description: "Encrypts sensitive data for protection", date: "2026-04-23 12:30pm", checked: false },
    { id: 29, name: "Blockchain Ledger", purpose: "Decentralized transactions Decentralized transactions", description: "Uses blockchain for secure record-keeping", date: "2026-05-10 12:30pm", checked: false },
    { id: 30, name: "Ad Management", purpose: "Marketing Marketing", description: "Manages and optimizes digital ad campaigns", date: "2026-06-14 12:30pm", checked: false },
    { id: 31, name: "Voice Recognition", purpose: "AI interaction AI interaction", description: "Implements voice recognition for hands-free control", date: "2026-07-19 12:30pm", checked: false },
    { id: 32, name: "IoT Hub", purpose: "Smart device integration Smart device integration", description: "Connects and controls IoT devices centrally", date: "2026-08-21 12:30pm", checked: false },
    { id: 33, name: "AI Predictive", purpose: "Data forecasting Data forecasting", description: "Analyzes data trends for predictive insights", date: "2026-09-30 12:30pm", checked: false },
    { id: 34, name: "Bug Tracker", purpose: "Software debugging Software debugging", description: "Tracks and manages software bugs efficiently", date: "2026-10-11 12:30pm", checked: false },
    { id: 35, name: "Video Conferencing", purpose: "Remote collaboration Remote collaboration", description: "Facilitates online video meetings with teams", date: "2026-11-15 12:30pm", checked: false },
    { id: 36, name: "Cloud Storage", purpose: "Data storage Data storage", description: "Provides cloud storage solutions for businesses", date: "2026-12-20 12:30pm", checked: false },
    { id: 37, name: "Fitness Tracker", purpose: "Health monitoring Health monitoring", description: "Tracks fitness activity and health metrics", date: "2027-01-25 12:30pm", checked: false },
    { id: 38, name: "Parental Control", purpose: "Child safety Child safety", description: "Provides tools for monitoring and restricting content", date: "2027-02-17 12:30pm", checked: false },
    { id: 39, name: "CMS System", purpose: "Website management Website management", description: "Handles web content creation and updates", date: "2027-03-29 12:30pm", checked: false },
    { id: 40, name: "Booking System", purpose: "Reservation management Reservation management", description: "Manages online booking and scheduling systems", date: "2027-04-12 12:30pm", checked: false },
    { id: 41, name: "CRM Platform", purpose: "Customer relationship Customer relationship", description: "Centralizes customer interactions and sales tracking", date: "2027-05-14 12:30pm", checked: false },
    { id: 42, name: "Loyalty Program", purpose: "Customer retention Customer retention", description: "Rewards customer loyalty with points and discounts", date: "2027-06-18 12:30pm", checked: false },
    { id: 43, name: "Translation Engine", purpose: "Language conversion Language conversion", description: "Provides real-time language translation", date: "2027-07-22 12:30pm", checked: false },
    { id: 44, name: "Weather Forecast", purpose: "Climate insights Climate insights", description: "Offers accurate weather forecasts", date: "2027-08-30 12:30pm", checked: false },
    { id: 45, name: "ERP System", purpose: "Enterprise management Enterprise management", description: "Integrates business operations into a unified system", date: "2027-09-05 12:30pm", checked: false },
    { id: 46, name: "Gaming Platform", purpose: "Entertainment Entertainment", description: "Hosts online multiplayer gaming experiences", date: "2027-10-15 12:30pm", checked: false },
    { id: 47, name: "Virtual47 Reality", purpose: "Immersive experience Immersive experience", description: "Creates virtual reality experiences for users", date: "2027-11-10 12:30pm", checked: false },
    { id: 48, name: "AI48 Image Recognition", purpose: "Computer vision Computer vision", description: "Uses AI to analyze and classify images", date: "2027-12-20 12:30pm", checked: false },
    { id: 49, name: "Ticket49 Booking", purpose: "Event reservations Event reservations", description: "Handles online ticket sales and event bookings", date: "2028-01-15 12:30pm", checked: false },
    { id: 50, name: "Supply50 Chain", purpose: "Logistics tracking Logistics tracking", description: "Optimizes and tracks supply chain operations", date: "2028-02-25 12:30pm", checked: false }
     
];

// let arr = data.sort((a,b) => a.name.localeCompare(b.name) );
// console.log(data);

export default data;




//{id:11,name:"Authentication11 Module",
    //     purpose:"User security User security User security  User security ",
    //     description:"Manages user login, registration, and session handling with precission",
    //     date:"2024-01-15 12:30pm",checked:false},
    // {id:12,name:"Payment12 Gateway",purpose:"Transaction processing Transaction processing Transaction processing",description:"Integrates payment systems for secure online transactions",date:"2024-02-05 12:30pm",checked:false},
    // {id:13,name:"Notification13 System",purpose:"User engagement User engagement  User engagement User engagement",description:"Sends alerts and notifications via email, SMS, or push notifications",date:"2024-03-10 12:30pm",checked:false},
    // {id:14,name:"Analytics14 Dashboard",purpose:"Data visualization Data visualization Data visualization Data visualization",description:"Displays metrics and KPIs to monitor business performance",date:"2024-04-12 12:30pm",checked:false},
    // {id:15,name:"API15 Gateway",purpose:"Middleware for services Middleware for services Middleware for services",description:"Routes, authenticates, and processes API requests efficiently",date:"2024-05-22 12:30pm",checked:false},
    // {id:16,name:"Inventory16 Manager",purpose:"Stock tracking Stock tracking  Stock tracking Stock tracking ",description:"Routes, authenticates, and processes API requests efficiently",date:"2024-06-15 12:30pm",checked:false},
    // {id:17,name:"Chatbot17 Assistant",purpose:"User interaction automation User interaction automation",description:"Provides automated responses and assistance to user queries",date:"2024-07-20 12:30pm",checked:false},
    // {id:18,name:"Logging18 System",purpose:"Application monitoring Application monitoring Application monitoring",description:"Captures application logs for debugging and performance monitoring",date:"2024-08-01 12:30pm",checked:false},
    // {id:19,name:"User19 Profile Manager",purpose:"Data management Data management Data management Data management",description:"Handles user details, preferences, and account settings,",date:"2024-09-18 12:30pm",checked:false},
    // {id:20,name:"Content20 Management",purpose:"Website management Website management Website management",description:"Organizes, updates, and publishes website content dynamically",date:"2024-10-15 12:30pm",checked:false},
    
    // {id:21,name:"Authentication21 Module",
    //     purpose:"User security User security User security  User security User security User security User security User security",
    //     description:"Manages user login, registration, and session handling with precission",
    //     date:"2024-01-15 12:30pm",checked:false},
    // {id:22,name:"Payment22 Gateway",purpose:"Transaction processing Transaction processing Transaction processing",description:"Integrates payment systems for secure online transactions",date:"2024-02-05 12:30pm",checked:false},
    // {id:23,name:"Notification23 System",purpose:"User engagement User engagement  User engagement User engagement",description:"Sends alerts and notifications via email, SMS, or push notifications",date:"2024-03-10 12:30pm",checked:false},
    // {id:24,name:"Analytics24 Dashboard",purpose:"Data visualization Data visualization Data visualization Data visualization",description:"Displays metrics and KPIs to monitor business performance",date:"2024-04-12 12:30pm",checked:false},
    // {id:25,name:"API25 Gateway",purpose:"Middleware for services Middleware for services Middleware for services",description:"Routes, authenticates, and processes API requests efficiently",date:"2024-05-22 12:30pm",checked:false},
    // {id:26,name:"Inventory26 Manager",purpose:"Stock tracking Stock tracking  Stock tracking Stock tracking ",description:"Routes, authenticates, and processes API requests efficiently",date:"2024-06-15 12:30pm",checked:false},
    // {id:27,name:"Chatbot27 Assistant",purpose:"User interaction automation User interaction automation",description:"Provides automated responses and assistance to user queries",date:"2024-07-20 12:30pm",checked:false},
    // {id:28,name:"Logging28 System",purpose:"Application monitoring Application monitoring Application monitoring",description:"Captures application logs for debugging and performance monitoring",date:"2024-08-01 12:30pm",checked:false},
    // {id:29,name:"User29 Profile Manager",purpose:"Data management Data management Data management Data management",description:"Handles user details, preferences, and account settings, ",date:"2024-09-18 12:30pm",checked:false},
    // {id:30,name:"Content30 Management",purpose:"Website management Website management Website management",description:"Organizes, updates, and publishes website content dynamically",date:"2024-10-15 12:30pm",checked:false},
